import { geminiQuestions } from "./gemini-pca.js";

const option = (id, text) => ({ id, text });
const q = (id, domain, type, prompt, options, correct, explanation, objective, caseStudy) => ({
  id, domain, type, prompt, options, correct, explanation, objective, ...(caseStudy ? { caseStudy } : {})
});
const h = (...args) => ({ ...q(...args), difficulty: "hardcore-legacy" });
const x = (...args) => ({ ...q(...args), difficulty: "hardcore" });

const caseStudies = [
  {
    id: "cymbal",
    name: "Cymbal Retail",
    industry: "Global retail",
    summary: "Cymbal Retail operates stores and a fast-growing ecommerce platform. It wants consistent customer experiences, near-real-time inventory visibility, and personalized recommendations.",
    requirements: ["Handle unpredictable seasonal traffic", "Reduce operational overhead", "Protect payment and customer data", "Use governed data for analytics and AI"],
    constraints: ["Existing store systems must remain during migration", "Small platform operations team", "Changes must avoid interrupting checkout"]
  },
  {
    id: "ehr",
    name: "EHR Healthcare",
    industry: "Healthcare",
    summary: "EHR Healthcare is modernizing clinical data exchange and analytics while keeping protected health information secure and available to clinicians.",
    requirements: ["Meet healthcare privacy obligations", "Share standards-based clinical data", "Support analytics without exposing PHI", "Maintain auditable access"],
    constraints: ["Legacy systems cannot move at once", "Strict data residency and retention rules", "Clinical applications require high availability"]
  },
  {
    id: "altostrat",
    name: "Altostrat Media",
    industry: "Media",
    summary: "Altostrat Media distributes live and on-demand content globally and wants to automate media enrichment with generative AI while controlling cost.",
    requirements: ["Low-latency global delivery", "Process bursty media pipelines", "Ground AI outputs in approved content", "Measure quality and spend"],
    constraints: ["Large existing media archive", "Rights vary by geography", "Launch deadlines are fixed"]
  },
  {
    id: "knight",
    name: "KnightMotives Automotive",
    industry: "Automotive",
    summary: "KnightMotives Automotive collects telemetry from connected vehicles and is developing AI-assisted diagnostics for service teams.",
    requirements: ["Ingest high-volume telemetry", "Keep vehicle services available", "Deploy models safely", "Enable controlled partner access"],
    constraints: ["Intermittent vehicle connectivity", "Safety-related changes require approval", "Manufacturing systems remain on premises"]
  }
];

const questions = [
  q("gcp-01","design","single","A global API must remain available through a regional outage and needs one anycast IP. Which design best meets the requirement?",[option("a","Regional external load balancers in two regions with DNS failover"),option("b","A global external Application Load Balancer with backends in multiple regions"),option("c","Cloud NAT in each region"),option("d","A single regional managed instance group")],["b"],"A global external Application Load Balancer provides a single anycast IP and can route to healthy multi-region backends.","High availability and failover"),
  q("gcp-02","design","single","A stateless HTTP container has unpredictable traffic and the team wants minimal operational overhead. What should you recommend?",[option("a","Cloud Run"),option("b","A sole-tenant Compute Engine VM"),option("c","A self-managed GKE cluster"),option("d","Bare Metal Solution")],["a"],"Cloud Run is a fully managed platform for stateless containers and scales with demand, including to zero.","Mapping compute needs to platform products"),
  q("gcp-03","design","multiple","Which TWO inputs are most important before selecting a disaster recovery architecture?",[option("a","Recovery time objective"),option("b","Recovery point objective"),option("c","Developer laptop model"),option("d","Resource label colors")],["a","b"],"RTO defines acceptable restoration time; RPO defines acceptable data loss. Together they drive DR architecture and cost.","Business continuity planning"),
  q("gcp-04","design","single","An application needs globally consistent relational transactions and horizontal scale. Which database is the best fit?",[option("a","Bigtable"),option("b","Spanner"),option("c","Cloud Storage"),option("d","Memorystore")],["b"],"Spanner provides relational semantics, strong consistency, and horizontal global scale.","Choosing storage types"),
  q("gcp-05","design","single","A company needs private, predictable connectivity from its data center to Google Cloud at high throughput. Which option should it choose?",[option("a","Direct Peering"),option("b","Dedicated Cloud Interconnect"),option("c","Cloud NAT"),option("d","Private Google Access")],["b"],"Dedicated Cloud Interconnect provides private high-throughput connectivity with predictable performance.","Hybrid connectivity"),
  q("gcp-06","design","single","A migration team first needs a fact-based inventory and dependency view of on-premises workloads. What should it use?",[option("a","Migration Center"),option("b","Cloud Scheduler"),option("c","Certificate Authority Service"),option("d","Cloud Deploy")],["a"],"Migration Center supports discovery, assessment, and planning for cloud migrations.","Creating a migration plan"),
  q("gcp-07","provision","single","Multiple application teams need centrally managed networking while owning their service projects. Which design is appropriate?",[option("a","Shared VPC"),option("b","VPC Network Peering between every project"),option("c","One project for the entire company"),option("d","Public IP addresses only")],["a"],"Shared VPC centralizes network administration in a host project while teams use service projects.","Resource hierarchy and networking"),
  q("gcp-08","provision","multiple","Which TWO controls help prevent accidental overspending while preserving visibility?",[option("a","Budgets with alerting"),option("b","Quotas"),option("c","Disable Cloud Billing reports"),option("d","Grant Owner to every developer")],["a","b"],"Budgets provide notifications and quotas constrain resource consumption. Budgets do not automatically cap spend.","Cost controls"),
  q("gcp-09","provision","single","An organization wants to enforce that resources can be created only in approved regions. What should it configure?",[option("a","An organization policy constraint"),option("b","A dashboard filter"),option("c","A billing export"),option("d","A Cloud DNS policy")],["a"],"Organization Policy constraints provide centralized guardrails, including resource location restrictions.","Resource hierarchy and policies"),
  q("gcp-10","provision","single","A platform team wants repeatable, reviewable infrastructure deployment across environments. What is the best approach?",[option("a","Manually click through the console"),option("b","Use Terraform through a controlled CI/CD workflow"),option("c","Share an Owner account"),option("d","Run commands from personal laptops")],["b"],"Infrastructure as code in CI/CD enables review, repeatability, policy checks, and an audit trail.","Infrastructure as code"),
  q("gcp-11","security","single","A workload on GKE needs to call a Google Cloud API without storing service account keys. What should you use?",[option("a","Workload Identity Federation for GKE"),option("b","A JSON key in a ConfigMap"),option("c","A shared user password"),option("d","An API key committed to source")],["a"],"Workload Identity Federation for GKE maps Kubernetes identities to IAM without long-lived keys.","Secure workload identity"),
  q("gcp-12","security","multiple","Which TWO practices best apply least privilege?",[option("a","Grant predefined narrow roles at the lowest practical resource"),option("b","Use separate service accounts per workload"),option("c","Grant basic Owner roles at organization level"),option("d","Share one service account across all applications")],["a","b"],"Narrow roles, limited scope, and distinct workload identities reduce unnecessary access and blast radius.","IAM best practices"),
  q("gcp-13","security","single","Security requires a centralized view of misconfigurations, vulnerabilities, and threats across the organization. Which service fits?",[option("a","Security Command Center"),option("b","Cloud Shell"),option("c","Cloud CDN"),option("d","Cloud Scheduler")],["a"],"Security Command Center provides centralized security posture and threat findings.","Security monitoring"),
  q("gcp-14","security","single","A regulated workload requires the customer to control key rotation and destruction for data-at-rest encryption. What should be used?",[option("a","Cloud KMS customer-managed encryption keys"),option("b","Base64 encoding"),option("c","Default network encryption only"),option("d","Public certificate authorities")],["a"],"CMEK with Cloud KMS gives the customer control over key lifecycle and access.","Encryption key management"),
  q("gcp-15","security","single","Administrators need SSH access to private VMs without public IP addresses or a bastion host. What should you recommend?",[option("a","Identity-Aware Proxy TCP forwarding"),option("b","Open port 22 to the internet"),option("c","Cloud CDN"),option("d","Public load balancer")],["a"],"IAP TCP forwarding provides identity-aware administrative access without public VM IPs.","Secure remote access"),
  q("gcp-16","process","single","A service repeatedly misses reliability targets because feature work always takes priority. What should the architect introduce?",[option("a","SLOs and an error-budget policy"),option("b","More manual deployments"),option("c","A larger VM without measurement"),option("d","Disable alerts")],["a"],"SLOs and error budgets make reliability measurable and create a decision mechanism for balancing risk and velocity.","Reliability process"),
  q("gcp-17","process","multiple","Which TWO actions best support a blameless root-cause analysis?",[option("a","Build a timeline from evidence"),option("b","Track corrective actions with owners"),option("c","Identify one person to punish"),option("d","Hide contributing process failures")],["a","b"],"Effective post-incident analysis focuses on evidence, systemic contributors, and owned follow-up actions.","Troubleshooting and RCA"),
  q("gcp-18","process","single","Leadership needs to compare the business value of migration waves. Which measure is most useful?",[option("a","A KPI tied to business outcomes and total cost"),option("b","Number of console clicks"),option("c","Number of products mentioned"),option("d","Lines of Terraform")],["a"],"Architecture success should be measured with business-aligned outcomes, costs, and agreed KPIs.","Business decision making"),
  q("gcp-19","implementation","single","A team must expose APIs to partners with quotas, analytics, versioning, and developer onboarding. Which product should it evaluate?",[option("a","Apigee"),option("b","Cloud NAT"),option("c","Filestore"),option("d","Cloud Router")],["a"],"Apigee provides full lifecycle API management including policies, quotas, analytics, and developer experiences.","API management"),
  q("gcp-20","implementation","single","A release must progress through environments with approvals and automated rollback support. Which service is designed for this?",[option("a","Cloud Deploy"),option("b","Cloud DNS"),option("c","Cloud Billing"),option("d","Cloud Interconnect")],["a"],"Cloud Deploy manages delivery pipelines and promotion of releases to GKE and Cloud Run targets.","Release management"),
  q("gcp-21","implementation","multiple","Which TWO tests provide the strongest evidence before a major production migration?",[option("a","Representative load testing"),option("b","Failover and recovery validation"),option("c","Only a developer smoke test"),option("d","A slide-deck review")],["a","b"],"Load and recovery tests validate critical performance and resilience assumptions before migration.","Testing and validation"),
  q("gcp-22","operations","single","Users report intermittent high latency. The team needs to follow a request across several microservices. Which signal is most useful?",[option("a","Distributed traces"),option("b","Billing invoices"),option("c","Organization policies"),option("d","DNS registration records")],["a"],"Distributed tracing correlates a request across services and reveals latency contributions.","Observability"),
  q("gcp-23","operations","multiple","Which TWO alerting practices reduce noise while protecting user experience?",[option("a","Alert on symptoms tied to SLOs"),option("b","Include actionable runbooks"),option("c","Page on every debug log"),option("d","Use the same threshold for every service")],["a","b"],"SLO-based symptom alerts and actionable runbooks focus responders on meaningful, diagnosable problems.","Alerting strategy"),
  q("gcp-24","operations","single","A team wants to validate that a regional failover process works before an incident. What should it do?",[option("a","Run a controlled failure exercise"),option("b","Assume the design works"),option("c","Wait for a real outage"),option("d","Only inspect the architecture diagram")],["a"],"Controlled failure exercises validate assumptions, automation, monitoring, and team readiness.","Reliability testing"),
  q("gcp-25","design","single","Cymbal Retail needs an event backbone to decouple checkout events from inventory and analytics consumers. What should it use?",[option("a","Pub/Sub"),option("b","Persistent Disk snapshots"),option("c","Cloud DNS"),option("d","A shared CSV file")],["a"],"Pub/Sub decouples event producers and consumers and scales for asynchronous delivery.","Integration patterns","cymbal"),
  q("gcp-26","security","single","Cymbal Retail wants analysts to use customer data while reducing exposure of sensitive identifiers. What should it use first to discover and transform the data?",[option("a","Sensitive Data Protection"),option("b","Cloud CDN"),option("c","Cloud Router"),option("d","Cloud Build")],["a"],"Sensitive Data Protection can discover, classify, inspect, and de-identify sensitive data.","Data protection","cymbal"),
  q("gcp-27","operations","single","Cymbal Retail expects a flash sale. Which preparation most directly validates checkout readiness?",[option("a","Load test against defined SLOs using representative traffic"),option("b","Increase every quota without measurement"),option("c","Disable autoscaling"),option("d","Move all services to one VM")],["a"],"Representative load testing against SLOs validates capacity, scaling, and user-impact targets.","Performance validation","cymbal"),
  q("gcp-28","security","single","EHR Healthcare needs a standards-based store for clinical data such as FHIR resources. Which service is the best fit?",[option("a","Cloud Healthcare API"),option("b","Cloud CDN"),option("c","Artifact Registry"),option("d","Cloud Tasks")],["a"],"Cloud Healthcare API supports healthcare data standards including FHIR.","Industry solutions","ehr"),
  q("gcp-29","security","multiple","EHR Healthcare must make PHI access auditable and tightly controlled. Which TWO controls are most appropriate?",[option("a","Least-privilege IAM"),option("b","Cloud Audit Logs with protected retention"),option("c","Public bucket access"),option("d","Shared administrator accounts")],["a","b"],"Least-privilege IAM controls access; protected audit logs provide evidence of administrative and data access.","Compliance and audit","ehr"),
  q("gcp-30","design","single","EHR Healthcare needs analytics on clinical data without exposing direct identifiers. Which design is best?",[option("a","De-identify data before loading an analytics environment"),option("b","Give every analyst production database access"),option("c","Export PHI to public files"),option("d","Disable logging")],["a"],"De-identification and separation of analytics access reduce exposure while enabling useful analysis.","Privacy-aware architecture","ehr"),
  q("gcp-31","design","single","Altostrat Media needs to deliver cached video content to a global audience with low latency. What should it use?",[option("a","Cloud CDN with an external Application Load Balancer"),option("b","Cloud NAT"),option("c","A single VM with a public IP"),option("d","Cloud VPN")],["a"],"Cloud CDN caches content at Google's edge and integrates with external Application Load Balancers.","Global content delivery","altostrat"),
  q("gcp-32","design","single","Altostrat Media runs bursty, parallel video transformation jobs. Which approach minimizes idle capacity management?",[option("a","A managed event-driven pipeline with autoscaling workers"),option("b","A permanently oversized VM"),option("c","A developer workstation"),option("d","Manual processing")],["a"],"Managed, autoscaling processing handles bursty parallel work without paying to manage idle fixed capacity.","Scalable processing","altostrat"),
  q("gcp-33","security","single","Altostrat Media must prevent its generative AI assistant from answering with unapproved content. Which design is best?",[option("a","Ground responses on an approved, access-controlled corpus and evaluate outputs"),option("b","Let the model answer from any public source"),option("c","Remove all monitoring"),option("d","Store prompts in public logs")],["a"],"Grounding on governed sources plus evaluation reduces unsupported and unauthorized responses.","Secure generative AI","altostrat"),
  q("gcp-34","design","single","KnightMotives must ingest telemetry from millions of vehicles and allow independent consumers to process it. What should it use?",[option("a","Pub/Sub"),option("b","A single Cloud SQL connection"),option("c","Email attachments"),option("d","Filestore mounted over the internet")],["a"],"Pub/Sub provides scalable asynchronous ingestion and decouples telemetry producers from consumers.","Event ingestion","knight"),
  q("gcp-35","implementation","multiple","KnightMotives is deploying an AI diagnostic model used by service technicians. Which TWO practices reduce rollout risk?",[option("a","Canary the model and monitor quality metrics"),option("b","Keep a versioned rollback path"),option("c","Replace all production traffic immediately"),option("d","Skip human approval for safety-related changes")],["a","b"],"A monitored canary and rollback path limit impact and support controlled recovery.","Safe model deployment","knight"),
  q("gcp-36","security","single","KnightMotives partners need controlled access to selected APIs without access to internal services. What should it use?",[option("a","An API management layer with scoped credentials and quotas"),option("b","Organization-wide Owner roles"),option("c","A shared root password"),option("d","Publicly expose every internal endpoint")],["a"],"API management provides a controlled partner boundary with authentication, authorization, quotas, and analytics.","Partner access","knight"),
  q("gcp-37","design","single","A batch analytics workload can tolerate interruptions and needs to minimize compute cost. Which resource is most appropriate?",[option("a","Spot VMs"),option("b","Sole-tenant nodes"),option("c","A permanently running high-memory VM"),option("d","Premium Support")],["a"],"Spot VMs offer substantial discounts for fault-tolerant workloads that can handle preemption.","Cost-optimized compute"),
  q("gcp-38","provision","single","Finance needs detailed Google Cloud cost data joined with internal cost-center data. What should the architect enable?",[option("a","Cloud Billing export to BigQuery"),option("b","Cloud CDN logs only"),option("c","A public Cloud Storage bucket"),option("d","DNS query logging")],["a"],"Exporting Cloud Billing data to BigQuery supports detailed analysis and joins with internal allocation data.","Cost visibility"),
  q("gcp-39","process","single","A migration requires application teams to adopt new operational responsibilities. What should the architect do first?",[option("a","Assess skills gaps and define a change-management plan"),option("b","Migrate everything without notifying teams"),option("c","Remove all existing runbooks"),option("d","Measure only infrastructure utilization")],["a"],"Skills readiness and change management are essential business-process inputs to a successful migration.","Change management"),
  q("gcp-40","operations","single","A service has a memory leak that develops slowly under production traffic. Which observability technique best helps identify the responsible code paths?",[option("a","Continuous profiling"),option("b","Billing budgets"),option("c","Organization Policy"),option("d","Cloud DNS forwarding")],["a"],"Continuous profiling reveals resource consumption by code path over time with low production overhead.","Profiling and benchmarking")
];

const hardcoreQuestions = [
  h("gcp-h01","design","single","A payment API runs in two regions behind a global external Application Load Balancer. Writes use a regional Cloud SQL HA instance with a cross-region read replica. The business requires RPO < 1 minute and automated regional failover without application changes. What is the most important architectural change?",[option("a","Promote the cross-region read replica automatically with Cloud Scheduler"),option("b","Migrate the write path to multi-region Spanner"),option("c","Add more Cloud SQL read replicas in the primary region"),option("d","Use Cloud CDN for payment requests")],["b"],"Cloud SQL cross-region replicas are asynchronous and promotion is not a transparent, zero-RPO regional failover mechanism. Spanner is the fitting managed relational choice for transparent multi-region writes and strong consistency.","Database failure-domain trade-offs"),
  h("gcp-h02","security","multiple","A regulated analytics platform uses BigQuery and Cloud Storage. Analysts must query approved data, but exfiltration to projects outside the organization must be constrained even if IAM is accidentally broadened. Which TWO controls best provide defense in depth?",[option("a","Put protected services inside a VPC Service Controls perimeter"),option("b","Apply organization policies that restrict resource sharing and allowed domains"),option("c","Use only dataset-level IAM"),option("d","Rely on Cloud Audit Logs to block exfiltration")],["a","b"],"VPC Service Controls reduces data-exfiltration risk at the service boundary, while organization policies add preventive governance. IAM and audit logs remain important but do not independently create the requested exfiltration boundary.","Data exfiltration controls"),
  h("gcp-h03","design","single","A global trading application requires single-digit millisecond reads in major markets, serializable transactions, and a five-nines availability target. Regulatory policy requires all writes to commit in the EU. Which design best addresses the requirements?",[option("a","Spanner multi-region configuration with the leader region in the EU and read-only replicas near users"),option("b","Bigtable clusters in every market with eventual consistency"),option("c","Cloud SQL cross-region replicas with writes distributed to every replica"),option("d","Firestore in Datastore mode with regional endpoints")],["a"],"A suitable Spanner multi-region configuration provides serializable transactions, high availability, and geographically placed replicas while leader placement controls write locality. Read latency and write locality must be considered together.","Global database topology"),
  h("gcp-h04","provision","single","An enterprise has hundreds of service projects attached to Shared VPCs. Security requires centrally enforced ingress controls that project owners cannot override, while application teams retain control of workload-specific rules. What should you implement?",[option("a","Hierarchical firewall policies at the organization or folder, with delegated lower-level rules"),option("b","Identical VPC firewall rules manually copied into every project"),option("c","Cloud Armor policies on every VM"),option("d","A single service account shared by all projects")],["a"],"Hierarchical firewall policies establish centrally governed controls at organization or folder level and can coexist with delegated workload-specific policy.","Enterprise network governance"),
  h("gcp-h05","design","multiple","A media pipeline receives unpredictable bursts of large files. Each file must be processed exactly once from the business perspective, but workers may retry or crash. Which TWO design choices are most important?",[option("a","Use an immutable event identifier and idempotent processing"),option("b","Persist processing state or deduplication results transactionally"),option("c","Set Pub/Sub acknowledgement deadlines to several days"),option("d","Assume Pub/Sub never redelivers an acknowledged message")],["a","b"],"Distributed messaging can redeliver. Exactly-once business outcomes require idempotency and durable deduplication or transactional state, regardless of delivery semantics.","Idempotent event processing"),
  h("gcp-h06","security","single","A CI pipeline in a third-party SaaS platform must deploy to Google Cloud. Security prohibits service account keys and requires short-lived, auditable credentials restricted to that pipeline identity. What is the best design?",[option("a","Workload Identity Federation with a narrowly scoped deployment service account"),option("b","Store a service account JSON key in the SaaS secret manager"),option("c","Grant the SaaS provider an organization Owner user account"),option("d","Allow unauthenticated deployment API calls from the SaaS IP range")],["a"],"Workload Identity Federation exchanges an external identity for short-lived Google credentials without long-lived service account keys and supports narrowly scoped impersonation.","Federated deployment identity"),
  h("gcp-h07","process","single","A business requests a 99.999% availability target for an internal reporting tool but will not fund multi-region operation or on-call coverage. What should the architect do first?",[option("a","Document the cost and operational implications, then negotiate an SLO aligned with business impact"),option("b","Accept the target and use a larger VM"),option("c","Define an error budget only after the first outage"),option("d","Promise the target because managed services always meet it")],["a"],"Reliability targets must reflect user experience, business impact, architecture, and operating model. The architect should expose trade-offs and align stakeholders before selecting technology.","Realistic reliability targets"),
  h("gcp-h08","operations","multiple","A service has a 99.9% monthly availability SLO. It consumed 70% of its monthly error budget in the first three days after two risky releases. Which TWO responses best follow SRE principles?",[option("a","Pause risky releases and prioritize reliability work"),option("b","Investigate release safety and improve automated rollback or canary controls"),option("c","Silence SLO alerts until next month"),option("d","Change the SLO retroactively so the service appears healthy")],["a","b"],"Rapid error-budget burn should trigger an agreed reliability response and improvements to the release process, not concealment or retroactive target changes.","Error-budget policy"),
  h("gcp-h09","design","single","A company must move 4 PB from an on-premises archive to Cloud Storage. Its network can spare only 2 Gbps, the first migration must finish within six weeks, and daily deltas must continue afterward. What is the best migration plan?",[option("a","Seed with Transfer Appliance, then use Storage Transfer Service for ongoing online deltas"),option("b","Use gsutil over the available link for the entire initial transfer"),option("c","Attach Persistent Disk to the on-premises servers"),option("d","Use Cloud CDN to upload the archive")],["a"],"At 2 Gbps, transferring 4 PB online cannot meet six weeks after overhead. An offline seed plus managed recurring online transfers addresses both initial volume and continuing deltas.","Large-scale data migration"),
  h("gcp-h10","security","single","A generative AI support assistant must use internal documents. Some documents contain secrets and hostile prompt-injection text. The assistant must not disclose secrets or follow instructions embedded in retrieved content. Which design is strongest?",[option("a","Govern and filter the corpus, apply least-privilege retrieval, use Model Armor and Sensitive Data Protection, and evaluate outputs"),option("b","Put every document into one public vector index"),option("c","Rely only on a system prompt that says not to reveal secrets"),option("d","Increase model temperature so attacks are less predictable")],["a"],"Secure generative AI requires layered controls across data governance, retrieval authorization, prompt and response protection, sensitive-data handling, and evaluation.","Secure AI architecture"),
  h("gcp-h11","provision","single","A latency-sensitive inference service needs GPUs during business hours, but demand varies sharply. Startup takes 20 minutes and GPU quota is scarce. Which approach best balances cost and availability?",[option("a","Use autoscaling with a scheduled minimum baseline, measured headroom, and quota reserved for expected peaks"),option("b","Scale to zero and assume GPUs are instantly available"),option("c","Run maximum GPU capacity continuously in every region"),option("d","Use Spot VMs for all synchronous production inference with no fallback")],["a"],"A measured baseline accounts for startup and quota constraints while autoscaling handles variability. Pure scale-to-zero or all-Spot designs risk availability; permanent peak capacity wastes cost.","AI infrastructure consumption trade-offs"),
  h("gcp-h12","implementation","multiple","A platform team wants to prevent vulnerable or unapproved container images from reaching production GKE clusters. Which TWO controls provide the strongest preventive supply-chain design?",[option("a","Generate attestations in a trusted build process and enforce them with Binary Authorization"),option("b","Scan artifacts and block deployments that violate policy"),option("c","Ask developers to inspect images manually after deployment"),option("d","Store images in a public registry to simplify access")],["a","b"],"Trusted attestations, Binary Authorization, vulnerability scanning, and policy enforcement create preventive software supply-chain controls before production deployment.","Software supply-chain security"),
  h("gcp-h13","design","single","A monolithic application has undocumented dependencies and a vendor license tied to physical CPU sockets. The data center lease ends in nine months. What is the best first migration disposition?",[option("a","Rehost the workload while validating licensing and dependencies, then modernize after the deadline risk is reduced"),option("b","Rewrite the entire application as microservices before discovering dependencies"),option("c","Move it directly to Cloud Run without assessment"),option("d","Deprecate it immediately because the license is complex")],["a"],"The deadline and unknown dependencies favor a staged disposition. Rehosting can reduce facility-exit risk, but licensing and dependency implications must be assessed before committing.","Migration disposition strategy"),
  h("gcp-h14","security","single","Developers need temporary production troubleshooting access. Policy requires approval, no standing privilege, and an audit trail. Which approach best meets the requirement?",[option("a","Use privileged access workflows with time-bound service account impersonation and audit logging"),option("b","Grant permanent Editor roles to the developer group"),option("c","Share the production service account password"),option("d","Add developers to the organization administrator group during incidents")],["a"],"Time-bound, approved impersonation removes standing privilege and produces auditable access without distributing credentials.","Just-in-time privileged access"),
  h("gcp-h15","design","multiple","A transactional service writes to Spanner and publishes events used for billing. The team observes occasional missing billing events after application crashes. Which TWO changes best address the consistency gap?",[option("a","Use a transactional outbox or change streams tied to committed database changes"),option("b","Make consumers idempotent"),option("c","Publish to Pub/Sub before starting the database transaction"),option("d","Increase the Pub/Sub retention period only")],["a","b"],"An outbox or change stream closes the dual-write gap between database commit and event publication. Idempotent consumers safely handle retries or duplicate delivery.","Transactional event consistency"),
  h("gcp-h16","operations","single","A regional service meets infrastructure uptime targets, but users still report failures during dependency degradation. What is the most useful next reliability improvement?",[option("a","Define user-journey SLIs and design graceful degradation for noncritical dependencies"),option("b","Measure VM CPU utilization more frequently"),option("c","Increase every instance size"),option("d","Exclude dependency failures from all monitoring")],["a"],"Reliability should be defined around user experience. User-journey SLIs expose dependency impact, and graceful degradation preserves critical functionality.","User-experience reliability"),
  h("gcp-h17","provision","single","A company needs private access from many consumer VPCs to a centrally operated service, including consumers with overlapping IP ranges. Producers must not manage peering routes for every consumer. What should it use?",[option("a","Private Service Connect"),option("b","Full-mesh VPC Network Peering"),option("c","Cloud NAT"),option("d","Public external IP addresses with allowlists")],["a"],"Private Service Connect provides service-oriented private connectivity without full network peering and supports consumers whose VPC address spaces overlap.","Private service connectivity"),
  h("gcp-h18","process","single","A migration program reports that 80% of servers have moved, but customer lead time and operating cost have not improved. What should the architect recommend?",[option("a","Reframe success metrics around business outcomes and optimize or retire workloads after migration"),option("b","Move the remaining servers faster and keep the same metrics"),option("c","Count migrated virtual CPUs instead"),option("d","Stop measuring costs until the migration is complete")],["a"],"Migration activity metrics do not prove business value. Outcome KPIs and post-migration optimization connect technical work to the intended benefits.","Business outcome measurement"),
  h("gcp-h19","security","multiple","A centralized security team must investigate activity across an organization while application teams must not alter or delete the retained evidence. Which TWO design choices are best?",[option("a","Use aggregated log sinks to a dedicated security project"),option("b","Apply restricted IAM and retention controls to the log destination"),option("c","Keep only application-local logs in each service project"),option("d","Grant project owners permission to delete the security log buckets")],["a","b"],"Aggregated sinks centralize evidence across the resource hierarchy; a dedicated destination with separation of duties and retention controls protects it from workload administrators.","Centralized audit evidence"),
  h("gcp-h20","design","single","Cymbal Retail wants personalized recommendations from governed customer data. Marketing needs rapid experimentation, security requires approved models and data boundaries, and operations requires reproducible promotion to production. What is the best architecture direction?",[option("a","Use Vertex AI pipelines and a governed feature/data workflow, register approved models, evaluate them, and promote through controlled deployment stages"),option("b","Let analysts upload arbitrary models directly to production endpoints"),option("c","Train models on developer laptops and email the artifacts"),option("d","Use one unversioned model endpoint and replace it manually")],["a"],"An orchestrated, governed ML lifecycle supports experimentation while preserving reproducibility, evaluation, approval, and controlled production deployment.","Governed ML lifecycle","cymbal"),
  x("gcp-h21","operations","multiple","A global service uses managed instance groups in three regions behind a global load balancer. During a partial dependency outage, instances remain healthy at the process level but return errors to users. Which TWO changes most directly improve automated traffic steering without causing unnecessary regional evacuation?",[option("a","Make the load-balancer health check exercise a representative dependency-aware readiness endpoint"),option("b","Use outlier detection or backend error-rate signals to eject unhealthy backends"),option("c","Shorten the instance group's autohealing check to restart every instance on any dependency error"),option("d","Configure DNS round-robin with a one-hour TTL"),option("e","Increase the maximum instance count in all regions")],["a","b"],"Readiness checks and backend-level outlier handling steer traffic away from impaired serving capacity. Aggressive autohealing can amplify dependency failures, while more capacity does not repair correctness.","Partial-failure traffic management"),
  x("gcp-h22","security","multiple","A company uses Shared VPC and GKE. Workloads must reach Google APIs privately, must not reach the public internet, and must be unable to copy BigQuery data to an attacker-controlled Google Cloud project. Which THREE controls collectively address these requirements?",[option("a","Private Google Access or Private Service Connect endpoints for Google APIs"),option("b","VPC Service Controls around the protected data services"),option("c","Egress firewall policy that denies unintended internet destinations"),option("d","Cloud NAT for every workload subnet"),option("e","Cloud Armor on the GKE nodes"),option("f","A larger secondary IP range for pods")],["a","b","c"],"Private API access removes the need for public paths, egress policy constrains internet destinations, and VPC Service Controls addresses service-to-service data exfiltration. Cloud NAT would enable internet egress rather than prohibit it.","Layered workload egress controls"),
  x("gcp-h23","design","single","An order service writes an order, reserves inventory, and charges a card through independently owned services. The business rejects distributed locking and two-phase commit. It requires recoverable processing, an audit trail, and automatic compensation when a later step fails. Which pattern is the best fit?",[option("a","A saga with persisted state, idempotent steps, and compensating transactions"),option("b","A synchronous request chain with long timeouts and retries"),option("c","A single Pub/Sub topic with no state store"),option("d","A globally distributed mutex held until all services respond"),option("e","A nightly reconciliation job as the only recovery mechanism")],["a"],"A persisted saga coordinates a long-running business transaction without distributed locking and provides explicit compensating actions, recovery, and auditability.","Distributed transaction coordination"),
  x("gcp-h24","provision","multiple","An organization wants application teams to create projects autonomously while enforcing central billing, mandatory labels, approved regions, default audit-log routing, and standard networking. Which THREE components form the strongest scalable landing-zone approach?",[option("a","A project factory implemented through reviewed infrastructure as code"),option("b","Organization policies and centrally managed hierarchy controls"),option("c","Aggregated log sinks and Shared VPC or centrally governed connectivity"),option("d","A document asking teams to configure controls manually"),option("e","One project shared by every workload"),option("f","Permanent organization Owner access for each team lead")],["a","b","c"],"A project factory plus preventive hierarchy policy and centralized networking/logging creates repeatable, governed autonomy. Manual instructions and broad ownership do not scale safely.","Enterprise landing-zone design"),
  x("gcp-h25","design","multiple","A company is migrating a latency-sensitive database from on premises. The application cannot tolerate more than 15 minutes of write downtime, the schema will change during migration, and rollback must remain possible until validation completes. Which THREE actions belong in the migration plan?",[option("a","Establish continuous replication or change-data capture before cutover"),option("b","Use a version-compatible schema transition that supports old and new application versions"),option("c","Define validation, cutover, and rollback criteria before the production event"),option("d","Take one backup on cutover day and assume it restores within 15 minutes"),option("e","Apply an irreversible schema change before replication starts"),option("f","Disable monitoring to reduce migration noise")],["a","b","c"],"Low-downtime reversible migrations require continuous data movement, compatible schema evolution, and rehearsed decision criteria. A backup alone does not guarantee the cutover or rollback time.","Reversible database migration"),
  x("gcp-h26","implementation","single","A GKE application passes tests but fails only in production after deployment. Pods can resolve a private service name, yet TCP connections time out. Production uses a Shared VPC and a newly created pod secondary range. What should you investigate first?",[option("a","Whether firewall policy permits traffic from the new pod secondary range to the private service"),option("b","Whether Cloud CDN is caching the private service response"),option("c","Whether the application's container image is stored in a multi-region Artifact Registry"),option("d","Whether the private service has an external DNS record"),option("e","Whether the deployment uses a rolling update rather than recreate")],["a"],"DNS success with TCP timeout and a new pod range strongly points to a network-policy or firewall source-range gap. The other changes do not explain the observed layer-4 failure.","Production network troubleshooting"),
  x("gcp-h27","operations","multiple","A team is designing alerts for an API with a 99.95% availability SLO. Traffic varies by two orders of magnitude between day and night. Which TWO alerting approaches best detect meaningful SLO risk while limiting noise?",[option("a","Use multi-window, multi-burn-rate alerts against the error budget"),option("b","Combine a fast-burn page with a slower-burn ticket or investigation alert"),option("c","Page whenever one request fails"),option("d","Alert only when CPU exceeds 80%"),option("e","Use the same fixed failed-request count threshold at all traffic levels")],["a","b"],"Burn-rate alerts scale with traffic and error-budget impact. Multiple windows balance fast detection with noise control; raw failure counts and CPU are not direct SLO-risk measures.","SLO burn-rate alerting"),
  x("gcp-h28","security","single","A workload uses a customer-managed encryption key. Security disables the key after detecting suspected compromise, causing a critical application outage. The company needs rapid recovery without weakening separation of duties. What is the best improvement?",[option("a","Create a documented, tested break-glass key-recovery process with tightly scoped approvers and audit alerts"),option("b","Grant the application team permanent Cloud KMS Admin on all keys"),option("c","Replace CMEK with application-embedded encryption keys"),option("d","Prevent security from disabling keys under any circumstance"),option("e","Use one key for every workload so recovery is simpler")],["a"],"CMEK introduces availability dependencies that require tested operational recovery. A controlled, auditable break-glass process preserves separation of duties while reducing outage duration.","CMEK operational resilience"),
  x("gcp-h29","design","single","A data platform ingests events into BigQuery. Analysts need corrected results within minutes when late events arrive up to seven days after event time. Queries must remain cost-efficient, and duplicates are possible. Which design best meets the requirement?",[option("a","Partition by event time, cluster on common filters or identifiers, and use an idempotent MERGE strategy for late data"),option("b","Partition by ingestion time and append every event without deduplication"),option("c","Create one unpartitioned table per customer and rebuild all tables nightly"),option("d","Stream into Cloud SQL and export the full database to BigQuery every minute"),option("e","Use Cloud Storage object creation time as the only source of truth")],["a"],"Event-time partitioning, useful clustering, and an idempotent update strategy support late corrections, deduplication, and efficient analytical access.","Late-arriving analytical data"),
  x("gcp-h30","process","multiple","An architecture review finds a proposed system technically meets requirements but has no ownership model, no capacity forecast, no rollback plan, and no cost allocation. Which TWO recommendations should block production launch most directly?",[option("a","Define operational ownership, SLOs, escalation paths, and tested recovery procedures"),option("b","Validate capacity assumptions and establish cost visibility or guardrails"),option("c","Rename the services to follow a consistent convention"),option("d","Add more diagrams to the design document without changing the design"),option("e","Delay all security review until after launch")],["a","b"],"An operable architecture needs ownership and recovery as well as validated capacity and financial controls. Naming and documentation polish do not compensate for missing operating mechanisms.","Production readiness review"),
  x("gcp-h31","design","multiple","A multi-region API stores user profiles in Spanner and large immutable media in Cloud Storage. EU profiles and media must remain in the EU, while US data must remain in the US. The API needs one global hostname and must route users to the correct residency boundary. Which THREE choices are most appropriate?",[option("a","Use separate regional or jurisdiction-specific data stores and buckets"),option("b","Determine residency before data access and route to the compliant backend"),option("c","Use a global external load balancer with controlled regional backends while preventing cross-boundary failover"),option("d","Use one unrestricted multi-region bucket for all media"),option("e","Replicate every profile globally to improve reads"),option("f","Allow automatic failover to any region regardless of residency")],["a","b","c"],"Residency must shape storage placement, routing, and failover policy together. A global entry point is compatible only when backend routing and failover preserve jurisdictional boundaries.","Residency-aware global architecture"),
  x("gcp-h32","implementation","single","A canary deployment shows normal error rate and latency, but business conversion drops significantly. Infrastructure metrics remain healthy. What should the release process do?",[option("a","Treat the business KPI as a release signal, halt or roll back the canary, and investigate"),option("b","Promote the canary because technical SLIs are healthy"),option("c","Increase canary traffic so conversion has more time to recover"),option("d","Disable conversion monitoring because it is not an infrastructure metric"),option("e","Resize the serving instances before examining the application change")],["a"],"Release health includes business outcomes when they represent user value. A technically healthy deployment can still be functionally harmful and should be stopped according to predefined guardrails.","Business-aware release safety"),
  x("gcp-h33","security","multiple","A partner must upload objects to one Cloud Storage prefix for 30 minutes. The partner has no Google identity. Security requires minimum privilege, no reusable long-lived credentials, and no ability to list or read existing objects. Which TWO design choices best satisfy the requirement?",[option("a","Issue narrowly scoped V4 signed URLs for specific object names and methods"),option("b","Use short expiration times and generate URLs only after the application authorizes each upload"),option("c","Create a service account key and send it to the partner"),option("d","Grant allUsers Storage Object Creator on the bucket"),option("e","Give the partner a signed URL for listing the bucket")],["a","b"],"Per-object, method-scoped, short-lived signed URLs provide temporary capability without a Google identity or listing/read access. Authorization before issuance preserves application policy.","Temporary external upload authorization"),
  x("gcp-h34","design","single","A team proposes active-active writes to two independent regional PostgreSQL databases and asynchronous bidirectional replication. The application requires uniqueness constraints and cannot tolerate conflicting accepted orders. Which response is most appropriate?",[option("a","Reject the topology unless the application can partition ownership or adopt a database with suitable global consistency"),option("b","Accept it because asynchronous replication guarantees conflict-free writes"),option("c","Increase replication frequency until uniqueness is guaranteed"),option("d","Add read replicas to both regions"),option("e","Use DNS weighted routing to prevent all write conflicts")],["a"],"Independent asynchronous writers cannot generally enforce global uniqueness or prevent conflicting committed orders. The design needs single-writer partitioning or a consistency model that meets the invariant.","Global write invariants"),
  x("gcp-h35","operations","multiple","A Cloud Run service calls a slow third-party API. During provider degradation, instance count and cost spike while successful throughput falls. Which THREE changes best prevent cascading resource exhaustion?",[option("a","Apply strict outbound deadlines and bounded retries with jitter"),option("b","Use a circuit breaker and shed or defer noncritical work"),option("c","Limit concurrency or queue depth based on measured dependency capacity"),option("d","Remove request timeouts so calls can eventually finish"),option("e","Retry every failure immediately from every instance"),option("f","Raise maximum instances without changing dependency behavior")],["a","b","c"],"Deadlines, bounded retries, circuit breaking, and backpressure prevent degraded dependencies from consuming unbounded resources. More retries or capacity can amplify the failure.","Dependency overload protection"),
  x("gcp-h36","provision","single","A central networking team uses Shared VPC. A service-project administrator can create VMs but new instances cannot attach to the intended host-project subnet. Existing instances work. What permission issue should you investigate first?",[option("a","Whether the service project's service agent or creating principal has Network User on the target subnet"),option("b","Whether the VM creator has Billing Account Administrator"),option("c","Whether the host project grants Storage Admin to the service project"),option("d","Whether the subnet has Private Google Access disabled"),option("e","Whether Cloud DNS logging is enabled")],["a"],"Attaching service-project resources to Shared VPC subnets requires the appropriate compute.networkUser permission on the subnet or host project. Existing instances do not prove new creators have it.","Shared VPC permission troubleshooting"),
  x("gcp-h37","design","multiple","A healthcare analytics team needs to join tokenized patient records with a restricted re-identification table. Analysts must never access direct identifiers, but an approved clinical workflow occasionally needs re-identification. Which THREE design elements are strongest?",[option("a","Separate tokenized analytics data from the re-identification mapping"),option("b","Use distinct identities and a tightly controlled service for approved re-identification"),option("c","Audit and alert on every re-identification operation"),option("d","Give analysts read access to both datasets but rely on policy"),option("e","Store the token and direct identifier in the same analytics table"),option("f","Disable logs to protect patient privacy")],["a","b","c"],"Separation, mediated privileged access, and complete auditing preserve analytical utility while constraining and evidencing re-identification.","Controlled re-identification"),
  x("gcp-h38","implementation","multiple","A Terraform pipeline manages production. A manual emergency change fixed an outage, causing configuration drift. Which TWO actions best restore control without undoing the valid fix?",[option("a","Import or reconcile the emergency change into code and review the resulting plan"),option("b","Add a tested emergency-change process that requires follow-up reconciliation"),option("c","Run an automatic apply immediately to force production back to the old state"),option("d","Ignore all future drift in production"),option("e","Give every responder permanent permission to bypass the pipeline")],["a","b"],"The valid emergency state should be reconciled into the source of truth before applying. A defined follow-up process makes necessary emergency changes compatible with infrastructure-as-code governance.","Infrastructure drift recovery"),
  x("gcp-h39","process","single","An executive asks whether to migrate a stable legacy system that has low operating cost, no growth, and a planned retirement in 18 months. Migration would consume a scarce engineering team for six months. What should the architect recommend?",[option("a","Compare migration cost and risk with the remaining business value, and consider retaining it until retirement"),option("b","Migrate immediately because every workload should be cloud native"),option("c","Rewrite it as microservices to improve the migration business case"),option("d","Buy committed use discounts before deciding whether to migrate"),option("e","Measure only the current server utilization")],["a"],"Migration is a business decision. When remaining lifetime and value are limited, retain or retire can be superior to spending scarce capacity on migration.","Migration business-case judgment"),
  x("gcp-h40","operations","single","A regional Spanner instance meets availability requirements, but an application deployment accidentally deletes critical rows. The team expected regional redundancy to protect the data. What is the most important correction?",[option("a","Add point-in-time recovery or backups and test logical data restoration procedures"),option("b","Add more read-write replicas in the same instance"),option("c","Move the application behind a global load balancer"),option("d","Increase node capacity"),option("e","Create a second application service account with the same permissions")],["a"],"High availability protects against infrastructure failure, not logical deletion. Recoverability requires independent data-protection mechanisms and tested restoration.","Availability versus recoverability")
];

export const gcpPca = {
  id: "gcp-pca",
  provider: "Google Cloud",
  certification: "Professional",
  title: "Professional Cloud Architect",
  code: "PCA",
  color: "#4285f4",
  durationMinutes: 120,
  officialQuestionRange: "50–60",
  description: "Design, secure, implement, and operate reliable Google Cloud solutions.",
  note: "This starter contains a condensed 40-question simulation. It preserves official domain weighting, exam pacing, multiple-select questions, and a 30% case-study mix.",
  domains: [
    { id: "design", name: "Designing and planning", weight: 25 },
    { id: "provision", name: "Managing and provisioning", weight: 17.5 },
    { id: "security", name: "Security and compliance", weight: 17.5 },
    { id: "process", name: "Analyzing and optimizing processes", weight: 15 },
    { id: "implementation", name: "Managing implementation", weight: 12.5 },
    { id: "operations", name: "Operations excellence", weight: 12.5 }
  ],
  caseStudies,
  questions: [...questions, ...hardcoreQuestions, ...geminiQuestions]
};
